package valkyrie.driver.redis;

import valkyrie.driver.suggestion.Suggestion;

import java.util.Collections;
import java.util.LinkedHashSet;
import java.util.Set;

/**
 * Redis 关键字
 *
 * @author Luo Tiansheng
 * @since 2026/5/7
 */
public class RedisSuggestions
{
        public static final Set<Suggestion> VALUES;

        static {
                Set<Suggestion> values = new LinkedHashSet<>();

                Collections.addAll(values,
                        // 连接与认证
                        Suggestion.ofFunction("AUTH"),
                        Suggestion.ofFunction("ECHO"),
                        Suggestion.ofFunction("HELLO"),
                        Suggestion.ofFunction("PING"),
                        Suggestion.ofFunction("QUIT"),
                        Suggestion.ofFunction("SELECT"),
                        Suggestion.ofFunction("SWAPDB"),
                        // 字符串操作
                        Suggestion.ofFunction("APPEND"),
                        Suggestion.ofFunction("DECR"),
                        Suggestion.ofFunction("DECRBY"),
                        Suggestion.ofFunction("GET"),
                        Suggestion.ofFunction("GETDEL"),
                        Suggestion.ofFunction("GETEX"),
                        Suggestion.ofFunction("GETRANGE"),
                        Suggestion.ofFunction("GETSET"),
                        Suggestion.ofFunction("INCR"),
                        Suggestion.ofFunction("INCRBY"),
                        Suggestion.ofFunction("INCRBYFLOAT"),
                        Suggestion.ofFunction("MGET"),
                        Suggestion.ofFunction("MSET"),
                        Suggestion.ofFunction("MSETNX"),
                        Suggestion.ofFunction("PSETEX"),
                        Suggestion.ofFunction("SET"),
                        Suggestion.ofFunction("SETBIT"),
                        Suggestion.ofFunction("SETEX"),
                        Suggestion.ofFunction("SETNX"),
                        Suggestion.ofFunction("SETRANGE"),
                        Suggestion.ofFunction("STRLEN"),
                        Suggestion.ofFunction("SUBSTR"),
                        // 列表操作
                        Suggestion.ofFunction("BLMOVE"),
                        Suggestion.ofFunction("BLPOP"),
                        Suggestion.ofFunction("BRPOP"),
                        Suggestion.ofFunction("BRPOPLPUSH"),
                        Suggestion.ofFunction("LINDEX"),
                        Suggestion.ofFunction("LINSERT"),
                        Suggestion.ofFunction("LLEN"),
                        Suggestion.ofFunction("LMOVE"),
                        Suggestion.ofFunction("LPOP"),
                        Suggestion.ofFunction("LPOS"),
                        Suggestion.ofFunction("LPUSH"),
                        Suggestion.ofFunction("LPUSHX"),
                        Suggestion.ofFunction("LRANGE"),
                        Suggestion.ofFunction("LREM"),
                        Suggestion.ofFunction("LSET"),
                        Suggestion.ofFunction("LTRIM"),
                        Suggestion.ofFunction("RPOP"),
                        Suggestion.ofFunction("RPOPLPUSH"),
                        Suggestion.ofFunction("RPUSH"),
                        Suggestion.ofFunction("RPUSHX"),
                        // 集合操作
                        Suggestion.ofFunction("SADD"),
                        Suggestion.ofFunction("SCARD"),
                        Suggestion.ofFunction("SDIFF"),
                        Suggestion.ofFunction("SDIFFSTORE"),
                        Suggestion.ofFunction("SINTER"),
                        Suggestion.ofFunction("SINTERSTORE"),
                        Suggestion.ofFunction("SISMEMBER"),
                        Suggestion.ofFunction("SMISMEMBER"),
                        Suggestion.ofFunction("SMEMBERS"),
                        Suggestion.ofFunction("SMOVE"),
                        Suggestion.ofFunction("SPOP"),
                        Suggestion.ofFunction("SRANDMEMBER"),
                        Suggestion.ofFunction("SREM"),
                        Suggestion.ofFunction("SSCAN"),
                        Suggestion.ofFunction("SUNION"),
                        Suggestion.ofFunction("SUNIONSTORE"),
                        // 有序集合操作
                        Suggestion.ofFunction("ZADD"),
                        Suggestion.ofFunction("ZCARD"),
                        Suggestion.ofFunction("ZCOUNT"),
                        Suggestion.ofFunction("ZDIFF"),
                        Suggestion.ofFunction("ZDIFFSTORE"),
                        Suggestion.ofFunction("ZINCRBY"),
                        Suggestion.ofFunction("ZINTER"),
                        Suggestion.ofFunction("ZINTERSTORE"),
                        Suggestion.ofFunction("ZLEXCOUNT"),
                        Suggestion.ofFunction("ZMSCORE"),
                        Suggestion.ofFunction("ZPOPMAX"),
                        Suggestion.ofFunction("ZPOPMIN"),
                        Suggestion.ofFunction("ZRANDMEMBER"),
                        Suggestion.ofFunction("ZRANGE"),
                        Suggestion.ofFunction("ZRANGEBYLEX"),
                        Suggestion.ofFunction("ZRANGEBYSCORE"),
                        Suggestion.ofFunction("ZRANK"),
                        Suggestion.ofFunction("ZREM"),
                        Suggestion.ofFunction("ZREMRANGEBYLEX"),
                        Suggestion.ofFunction("ZREMRANGEBYRANK"),
                        Suggestion.ofFunction("ZREMRANGEBYSCORE"),
                        Suggestion.ofFunction("ZREVRANGE"),
                        Suggestion.ofFunction("ZREVRANGEBYLEX"),
                        Suggestion.ofFunction("ZREVRANGEBYSCORE"),
                        Suggestion.ofFunction("ZREVRANK"),
                        Suggestion.ofFunction("ZSCORE"),
                        Suggestion.ofFunction("ZUNION"),
                        Suggestion.ofFunction("ZUNIONSTORE"),
                        // 哈希操作
                        Suggestion.ofFunction("HDEL"),
                        Suggestion.ofFunction("HEXISTS"),
                        Suggestion.ofFunction("HGET"),
                        Suggestion.ofFunction("HGETALL"),
                        Suggestion.ofFunction("HINCRBY"),
                        Suggestion.ofFunction("HINCRBYFLOAT"),
                        Suggestion.ofFunction("HKEYS"),
                        Suggestion.ofFunction("HLEN"),
                        Suggestion.ofFunction("HMGET"),
                        Suggestion.ofFunction("HMSET"),
                        Suggestion.ofFunction("HRANDFIELD"),
                        Suggestion.ofFunction("HSCAN"),
                        Suggestion.ofFunction("HSET"),
                        Suggestion.ofFunction("HSETNX"),
                        Suggestion.ofFunction("HSTRLEN"),
                        Suggestion.ofFunction("HVALS"),
                        // 超长文本/比特操作
                        Suggestion.ofFunction("BITCOUNT"),
                        Suggestion.ofFunction("BITFIELD"),
                        Suggestion.ofFunction("BITOP"),
                        Suggestion.ofFunction("BITPOS"),
                        Suggestion.ofFunction("GETBIT"),
                        Suggestion.ofFunction("SETBIT"),
                        // Geo 地理操作
                        Suggestion.ofFunction("GEOADD"),
                        Suggestion.ofFunction("GEODIST"),
                        Suggestion.ofFunction("GEOHASH"),
                        Suggestion.ofFunction("GEOPOS"),
                        Suggestion.ofFunction("GEORADIUS"),
                        Suggestion.ofFunction("GEORADIUSBYMEMBER"),
                        Suggestion.ofFunction("GEOSEARCH"),
                        Suggestion.ofFunction("GEOSEARCHSTORE"),
                        // Stream 流操作
                        Suggestion.ofFunction("XACK"),
                        Suggestion.ofFunction("XADD"),
                        Suggestion.ofFunction("XAUTOCLAIM"),
                        Suggestion.ofFunction("XCLAIM"),
                        Suggestion.ofFunction("XDEL"),
                        Suggestion.ofFunction("XGROUP"),
                        Suggestion.ofFunction("XINFO"),
                        Suggestion.ofFunction("XLEN"),
                        Suggestion.ofFunction("XPENDING"),
                        Suggestion.ofFunction("XRANGE"),
                        Suggestion.ofFunction("XREAD"),
                        Suggestion.ofFunction("XREADGROUP"),
                        Suggestion.ofFunction("XREVRANGE"),
                        Suggestion.ofFunction("XTRIM"),
                        // 键操作
                        Suggestion.ofFunction("COPY"),
                        Suggestion.ofFunction("DEL"),
                        Suggestion.ofFunction("EXISTS"),
                        Suggestion.ofFunction("EXPIRE"),
                        Suggestion.ofFunction("EXPIREAT"),
                        Suggestion.ofFunction("KEYS"),
                        Suggestion.ofFunction("MOVE"),
                        Suggestion.ofFunction("OBJECT"),
                        Suggestion.ofFunction("PERSIST"),
                        Suggestion.ofFunction("PEXPIRE"),
                        Suggestion.ofFunction("PEXPIREAT"),
                        Suggestion.ofFunction("PTTL"),
                        Suggestion.ofFunction("RANDOMKEY"),
                        Suggestion.ofFunction("RENAME"),
                        Suggestion.ofFunction("RENAMENX"),
                        Suggestion.ofFunction("RESTORE"),
                        Suggestion.ofFunction("SORT"),
                        Suggestion.ofFunction("TOUCH"),
                        Suggestion.ofFunction("TTL"),
                        Suggestion.ofFunction("TYPE"),
                        Suggestion.ofFunction("UNLINK"),
                        Suggestion.ofFunction("WAIT"),
                        Suggestion.ofFunction("WATCH"),
                        Suggestion.ofFunction("UNWATCH"),
                        // 数据库操作
                        Suggestion.ofFunction("DBSIZE"),
                        Suggestion.ofFunction("FLUSHALL"),
                        Suggestion.ofFunction("FLUSHDB"),
                        Suggestion.ofFunction("LASTSAVE"),
                        Suggestion.ofFunction("SAVE"),
                        // 脚本与事务
                        Suggestion.ofFunction("EVAL"),
                        Suggestion.ofFunction("EVALSHA"),
                        Suggestion.ofFunction("EVALSHA_RO"),
                        Suggestion.ofFunction("EVAL_RO"),
                        Suggestion.ofFunction("FCALL"),
                        Suggestion.ofFunction("FCALL_RO"),
                        Suggestion.ofFunction("SCRIPT"),
                        Suggestion.ofFunction("DEBUG"),
                        Suggestion.ofFunction("MULTI"),
                        Suggestion.ofFunction("EXEC"),
                        Suggestion.ofFunction("DISCARD"),
                        // 集群操作
                        Suggestion.ofKeyword("CLUSTER"),
                        Suggestion.ofFunction("READONLY"),
                        Suggestion.ofFunction("READWRITE"),
                        Suggestion.ofFunction("REPLICAOF"),
                        Suggestion.ofFunction("SLAVEOF"),
                        Suggestion.ofFunction("ROLE"),
                        // 慢查询与监控
                        Suggestion.ofFunction("SLOWLOG"),
                        Suggestion.ofFunction("LATENCY"),
                        Suggestion.ofFunction("MONITOR"),
                        Suggestion.ofFunction("MEMORY"),
                        Suggestion.ofFunction("INFO"),
                        // 配置与服务器
                        Suggestion.ofKeyword("ACL"),
                        Suggestion.ofFunction("ACL_CAT"),
                        Suggestion.ofFunction("ACL_DELUSER"),
                        Suggestion.ofFunction("ACL_DRYRUN"),
                        Suggestion.ofFunction("ACL_GETUSER"),
                        Suggestion.ofFunction("ACL_LIST"),
                        Suggestion.ofFunction("ACL_LOAD"),
                        Suggestion.ofFunction("ACL_LOG"),
                        Suggestion.ofFunction("ACL_SETUSER"),
                        Suggestion.ofFunction("ACL_USERS"),
                        Suggestion.ofFunction("ACL WHOAMI"),
                        Suggestion.ofFunction("BGREWRITEAOF"),
                        Suggestion.ofFunction("BGSAVE"),
                        Suggestion.ofFunction("COMMAND"),
                        Suggestion.ofFunction("COMMAND COUNT"),
                        Suggestion.ofFunction("COMMAND DOCS"),
                        Suggestion.ofFunction("COMMAND GETKEYS"),
                        Suggestion.ofFunction("COMMAND GETKEYSANDFLAGS"),
                        Suggestion.ofFunction("COMMAND INFO"),
                        Suggestion.ofFunction("COMMAND LIST"),
                        Suggestion.ofKeyword("CONFIG"),
                        Suggestion.ofFunction("FAILOVER"),
                        Suggestion.ofKeyword("MODULE"),
                        Suggestion.ofFunction("MODULE LIST"),
                        Suggestion.ofFunction("MODULE LOAD"),
                        Suggestion.ofFunction("MODULE UNLOAD"),
                        Suggestion.ofFunction("PUBLISH"),
                        Suggestion.ofKeyword("PUBSUB"),
                        Suggestion.ofFunction("PSUBSCRIBE"),
                        Suggestion.ofFunction("PUNSUBSCRIBE"),
                        Suggestion.ofFunction("SHUTDOWN"),
                        Suggestion.ofFunction("SUBSCRIBE"),
                        Suggestion.ofFunction("UNSUBSCRIBE"),
                        // 哨兵
                        Suggestion.ofKeyword("SENTINEL"),
                        Suggestion.ofFunction("MASTERS"),
                        Suggestion.ofFunction("SLAVES"),
                        Suggestion.ofFunction("GET"),
                        Suggestion.ofFunction("RESET"),
                        Suggestion.ofFunction("FAILOVER"),
                        Suggestion.ofFunction("SET"),
                        Suggestion.ofFunction("MONITOR"),
                        Suggestion.ofFunction("REMOVE"),
                        Suggestion.ofFunction("CKQUORUM"),
                        Suggestion.ofFunction("DEBUG"),
                        Suggestion.ofFunction("FLUSHCONFIG"),
                        Suggestion.ofFunction("GETMASTER"),
                        Suggestion.ofFunction("HARD_RESET"),
                        Suggestion.ofFunction("IS_MASTER_DOWN_BY_ADDR"),
                        Suggestion.ofKeyword("MASTER"),
                        Suggestion.ofFunction("MYID"),
                        Suggestion.ofFunction("pending"),
                        Suggestion.ofFunction("POSTRUN"),
                        Suggestion.ofFunction("PREREQUISITES"),
                        Suggestion.ofFunction("SOFT_RESET")
                );

                VALUES = Collections.unmodifiableSet(values);
        }

        private RedisSuggestions()
        {
                /* DO NOTHING... */
        }
}