package valkyrie.driver.dm;

import valkyrie.driver.suggestion.Suggestion;
import valkyrie.driver.suggestion.SqlStandardSuggestions;

import java.util.Collections;
import java.util.LinkedHashSet;
import java.util.Set;

/**
 * 达梦标准关键字
 *
 * @author Luo Tiansheng
 * @since 2026/5/7
 */
public class DMSuggestions
{
        public static final Set<Suggestion> VALUES;

        static {
                Set<Suggestion> values = new LinkedHashSet<>();

                Collections.addAll(values,
                        // 系统函数
                        Suggestion.ofFunction("SYSDATE"),
                        Suggestion.ofFunction("SYSTIMESTAMP"),
                        Suggestion.ofFunction("UID"),
                        Suggestion.ofKeyword("USER"),
                        Suggestion.ofFunction("USERENV"),
                        Suggestion.ofFunction("SYS_GUID"),
                        Suggestion.ofFunction("FROM_BASE64"),
                        // 层次查询
                        Suggestion.ofFunction("CONNECT_BY_ISCYCLE"),
                        Suggestion.ofFunction("CONNECT_BY_ISLEAF"),
                        Suggestion.ofFunction("CONNECT_BY_ROOT"),
                        Suggestion.ofKeyword("PRIOR"),
                        Suggestion.ofKeyword("LEVEL"),
                        // 序列
                        Suggestion.ofKeyword("CURRVAL"),
                        Suggestion.ofKeyword("NEXTVAL"),
                        Suggestion.ofKeyword("INCREMENT"),
                        Suggestion.ofKeyword("CYCLE"),
                        Suggestion.ofKeyword("NOMAXVALUE"),
                        Suggestion.ofKeyword("NOMINVALUE"),
                        Suggestion.ofKeyword("MAXSIZE"),
                        Suggestion.ofKeyword("MINEXTENTS"),
                        Suggestion.ofKeyword("MAXEXTENTS"),
                        Suggestion.ofKeyword("CACHE"),
                        Suggestion.ofKeyword("NOCACHE"),
                        Suggestion.ofKeyword("ORDER"),
                        Suggestion.ofKeyword("NOORDER"),
                        // 表空间与数据文件
                        Suggestion.ofKeyword("TABLESPACE"),
                        Suggestion.ofKeyword("DATAFILE"),
                        Suggestion.ofKeyword("DBFILE"),
                        Suggestion.ofKeyword("TEMPFILE"),
                        Suggestion.ofKeyword("TEMP"),
                        Suggestion.ofKeyword("UNDO"),
                        Suggestion.ofKeyword("ONLINE"),
                        Suggestion.ofKeyword("OFFLINE"),
                        Suggestion.ofKeyword("AUTOEXTEND"),
                        Suggestion.ofKeyword("NEXT"),
                        Suggestion.ofKeyword("UNLIMITED"),
                        Suggestion.ofKeyword("FREELIST"),
                        Suggestion.ofKeyword("FREELISTS"),
                        Suggestion.ofKeyword("PCTFREE"),
                        Suggestion.ofKeyword("PCTUSED"),
                        Suggestion.ofKeyword("INITRANS"),
                        Suggestion.ofKeyword("MAXTRANS"),
                        // 归档与恢复
                        Suggestion.ofKeyword("ARCHIVELOG"),
                        Suggestion.ofKeyword("NOARCHIVELOG"),
                        Suggestion.ofKeyword("ARCHIVEDIR"),
                        Suggestion.ofKeyword("RECOVER"),
                        Suggestion.ofKeyword("BACKUP"),
                        Suggestion.ofKeyword("RESTORE"),
                        // 用户与权限
                        Suggestion.ofKeyword("IDENTIFIED"),
                        Suggestion.ofKeyword("AUTHID"),
                        Suggestion.ofKeyword("SYSDBA"),
                        Suggestion.ofKeyword("DBA"),
                        Suggestion.ofKeyword("PUBLIC"),
                        Suggestion.ofKeyword("PRIVATE"),
                        Suggestion.ofKeyword("ROLE"),
                        // 闪回
                        Suggestion.ofKeyword("AS OF"),
                        Suggestion.ofKeyword("TIMESTAMP"),
                        Suggestion.ofKeyword("SCN"),
                        Suggestion.ofKeyword("FLASHBACK"),
                        Suggestion.ofKeyword("VERSIONS"),
                        Suggestion.ofKeyword("MINING"),
                        // 约束
                        Suggestion.ofKeyword("DISABLE"),
                        Suggestion.ofKeyword("ENABLE"),
                        Suggestion.ofKeyword("VALIDATE"),
                        Suggestion.ofKeyword("NOVALIDATE"),
                        Suggestion.ofKeyword("DEFERRED"),
                        Suggestion.ofKeyword("IMMEDIATE"),
                        // 索引类型
                        Suggestion.ofKeyword("BITMAP"),
                        Suggestion.ofKeyword("HASH"),
                        Suggestion.ofKeyword("CLUSTER"),
                        Suggestion.ofKeyword("FUNCTION"),
                        Suggestion.ofKeyword("DOMAIN"),
                        // 会话与事务
                        Suggestion.ofKeyword("SESSION"),
                        Suggestion.ofKeyword("INSTANCE"),
                        Suggestion.ofKeyword("TRANSACTION"),
                        Suggestion.ofKeyword("MOUNT"),
                        Suggestion.ofKeyword("EXCLUSIVE"),
                        Suggestion.ofKeyword("RESOURCE"),
                        // PL/SQL 相关
                        Suggestion.ofKeyword("PRAGMA"),
                        Suggestion.ofKeyword("EXCEPTION"),
                        Suggestion.ofKeyword("RAISE"),
                        Suggestion.ofKeyword("ASSERT"),
                        Suggestion.ofKeyword("AUTONOMOUS_TRANSACTION"),
                        // 行列转换
                        Suggestion.ofKeyword("PIVOT"),
                        Suggestion.ofKeyword("UNPIVOT"),
                        Suggestion.ofKeyword("ANY"),
                        Suggestion.ofKeyword("SOME"),
                        // 分区
                        Suggestion.ofKeyword("PARTITION"),
                        Suggestion.ofKeyword("SUBPARTITION"),
                        Suggestion.ofKeyword("RANGE"),
                        Suggestion.ofKeyword("LIST"),
                        Suggestion.ofKeyword("VALUE"),
                        // 其他达梦特有
                        Suggestion.ofKeyword("ABORT"),
                        Suggestion.ofKeyword("AUTO"),
                        Suggestion.ofKeyword("BLOCKSIZE"),
                        Suggestion.ofKeyword("BLOCK_SIZE"),
                        Suggestion.ofKeyword("BUFFER"),
                        Suggestion.ofKeyword("COMMENT"),
                        Suggestion.ofKeyword("COMPRESS"),
                        Suggestion.ofKeyword("DECRYPT"),
                        Suggestion.ofKeyword("ENCRYPT"),
                        Suggestion.ofKeyword("EXIT"),
                        Suggestion.ofKeyword("FILE"),
                        Suggestion.ofKeyword("GLOBALLY"),
                        Suggestion.ofKeyword("KEEP"),
                        Suggestion.ofKeyword("LOGFILE"),
                        Suggestion.ofKeyword("LOGGING"),
                        Suggestion.ofKeyword("MODE"),
                        Suggestion.ofKeyword("NOCOMPRESS"),
                        Suggestion.ofKeyword("NOCYCLE"),
                        Suggestion.ofKeyword("NOLOGGING"),
                        Suggestion.ofKeyword("NOSORT"),
                        Suggestion.ofKeyword("NOWAIT"),
                        Suggestion.ofKeyword("NUMBER"),
                        Suggestion.ofKeyword("NVARCHAR"),
                        Suggestion.ofKeyword("NVARCHAR2"),
                        Suggestion.ofKeyword("PACKAGE"),
                        Suggestion.ofKeyword("PLAN"),
                        Suggestion.ofKeyword("RAW"),
                        Suggestion.ofKeyword("REUSE"),
                        Suggestion.ofKeyword("ROWID"),
                        Suggestion.ofKeyword("ROWNUM"),
                        Suggestion.ofKeyword("SEQUENCE"),
                        Suggestion.ofKeyword("SHARE"),
                        Suggestion.ofKeyword("SIZE"),
                        Suggestion.ofKeyword("SNAPSHOT"),
                        Suggestion.ofKeyword("SYNONYM"),
                        Suggestion.ofKeyword("THREAD"),
                        Suggestion.ofKeyword("TRIGGER"),
                        Suggestion.ofKeyword("VARCHAR"),
                        Suggestion.ofKeyword("VARCHAR2"),
                        Suggestion.ofKeyword("INT"),
                        Suggestion.ofKeyword("WAIT"),
                        Suggestion.ofKeyword("DUAL"),
                        Suggestion.ofKeyword("DECLARE"),
                        Suggestion.ofKeyword("END"),
                        Suggestion.ofKeyword("BODY"),
                        Suggestion.ofKeyword("FOR"),
                        Suggestion.ofKeyword("LOOP"),
                        Suggestion.ofKeyword("WHILE"),
                        Suggestion.ofKeyword("IF"),
                        Suggestion.ofKeyword("THEN"),
                        Suggestion.ofKeyword("ELSE"),
                        Suggestion.ofKeyword("ELSIF"),
                        Suggestion.ofKeyword("CASE"),
                        Suggestion.ofKeyword("WHEN"),
                        Suggestion.ofKeyword("RETURN"),
                        Suggestion.ofKeyword("OUT"),
                        Suggestion.ofKeyword("INOUT"),
                        Suggestion.ofKeyword("IS"),
                        Suggestion.ofKeyword("AS"),
                        Suggestion.ofKeyword("PROCEDURE"),
                        Suggestion.ofKeyword("TYPE"),
                        Suggestion.ofKeyword("RECORD"),
                        Suggestion.ofKeyword("TABLE"),
                        Suggestion.ofKeyword("VARRAY"),
                        Suggestion.ofKeyword("CURSOR"),
                        Suggestion.ofKeyword("OPEN"),
                        Suggestion.ofKeyword("CLOSE"),
                        Suggestion.ofKeyword("FETCH"),
                        Suggestion.ofKeyword("NULL"),
                        Suggestion.ofKeyword("TRUE"),
                        Suggestion.ofKeyword("FALSE"),
                        Suggestion.ofKeyword("DEFAULT"),
                        Suggestion.ofOperator("NOT"),
                        Suggestion.ofKeyword("UNIQUE"),
                        Suggestion.ofKeyword("CHECK"),
                        Suggestion.ofKeyword("PRIMARY"),
                        Suggestion.ofKeyword("FOREIGN"),
                        Suggestion.ofKeyword("REFERENCES"),
                        Suggestion.ofKeyword("CONSTRAINT"),
                        Suggestion.ofKeyword("INDEX"),
                        Suggestion.ofKeyword("VIEW"),
                        Suggestion.ofKeyword("GRANT"),
                        Suggestion.ofKeyword("REVOKE"),
                        Suggestion.ofKeyword("COMMIT"),
                        Suggestion.ofKeyword("ROLLBACK"),
                        Suggestion.ofKeyword("SET"),
                        Suggestion.ofKeyword("SHOW"),
                        Suggestion.ofKeyword("SVRMODE"),
                        Suggestion.ofKeyword("LINK"),
                        Suggestion.ofKeyword("DATABASE"),
                        Suggestion.ofKeyword("SCHEMA"),
                        Suggestion.ofKeyword("EXISTS"),
                        Suggestion.ofKeyword("PURGE"),
                        Suggestion.ofKeyword("REBUILD"),
                        Suggestion.ofKeyword("RENAME"),
                        Suggestion.ofKeyword("REPAIR"),
                        Suggestion.ofKeyword("STORAGE"),
                        Suggestion.ofKeyword("TRUNCATE"),
                        Suggestion.ofKeyword("UNDOFILE"),
                        Suggestion.ofKeyword("WORK"),
                        Suggestion.ofKeyword("RELEASE"),
                        Suggestion.ofKeyword("ROW"),
                        Suggestion.ofKeyword("ROWS"),
                        Suggestion.ofKeyword("ONLY"),
                        Suggestion.ofKeyword("GRAGMENT"),
                        Suggestion.ofKeyword("LOCATION"),
                        Suggestion.ofKeyword("REPLICATED"),
                        Suggestion.ofKeyword("LOCAL"),
                        Suggestion.ofKeyword("GLOBAL"),
                        Suggestion.ofKeyword("IMMUTABLE"),
                        Suggestion.ofKeyword("STABLE"),
                        Suggestion.ofKeyword("VOLATILE"),
                        Suggestion.ofKeyword("CALLED"),
                        Suggestion.ofKeyword("RETURNING"),
                        Suggestion.ofKeyword("BULK"),
                        Suggestion.ofKeyword("COLLECT"),
                        Suggestion.ofKeyword("FORALL"),
                        Suggestion.ofKeyword("LIMIT"),
                        Suggestion.ofKeyword("REJECT"),
                        Suggestion.ofKeyword("LOG"),
                        Suggestion.ofKeyword("SKIP"),
                        Suggestion.ofKeyword("SWAP"),
                        Suggestion.ofFunction("TRIM"),
                        Suggestion.ofFunction("CONCAT"),
                        Suggestion.ofKeyword("YEAR"),
                        Suggestion.ofKeyword("MONTH"),
                        Suggestion.ofKeyword("DAY"),
                        Suggestion.ofKeyword("HOUR"),
                        Suggestion.ofKeyword("MINUTE"),
                        Suggestion.ofKeyword("SECOND"),
                        Suggestion.ofKeyword("TIMEZONE"),
                        Suggestion.ofKeyword("TIME"),
                        Suggestion.ofFunction("FROM_BASE64"),
                        Suggestion.ofFunction("BINTOCHAR"),
                        // 代码片段
                        Suggestion.ofSnippet("de64", "BINTOCHAR(FROM_BASE64(${1:column_name}))")
                );

                values.addAll(SqlStandardSuggestions.VALUES);
                VALUES = Collections.unmodifiableSet(values);
        }

        private DMSuggestions()
        {
                /* DO NOTHING... */
        }
}